export const baseEndpoint =
  "https://us-central1-labenu-apis.cloudfunctions.net/labeX/fabio-epps";

export const auth = { headers: { auth: localStorage.getItem("token") } };

export const planets = [
  "Mercúrio",
  "Venus",
  "Terra",
  "Marte",
  "Jupiter",
  "Saturno",
  "Urano",
  "Netuno",
  "Plutão",
];

export const countries = [
  "Afeganistão",
  "África do Sul",
  "Albânia",
  "Alemanha",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antártida",
  "Antígua e Barbuda",
  "Arábia Saudita",
  "Argélia",
  "Argentina",
  "Armênia",
  "Aruba",
  "Austrália",
  "Áustria",
  "Azerbaijão",
  "Baamas",
  "Bangladesh",
  "Barbados",
  "Bahrein",
  "Bélgica",
  "Belize",
  "Benim",
  "Bermudas",
  "Bielorrússia",
  "Birmânia",
  "Bolívia",
  "Bósnia e Herzegovina",
  "Botsuana",
  "Brasil",
  "Brunei",
  "Bulgária",
  "Burquina Faso",
  "Burundi",
  "Butão",
  "Cabo Verde",
  "Camarões",
  "Camboja",
  "Canadá",
  "Catar",
  "Cazaquistão",
  "Chade",
  "Chile",
  "China",
  "Chipre",
  "Cisjordânia",
  "Ilha Clipperton",
  "Colômbia",
  "Comores",
  "Congo-Brazzaville",
  "Congo-Kinshasa",
  "Coreia do Norte",
  "Coreia do Sul",
  "Costa do Marfim",
  "Costa Rica",
  "Croácia",
  "Cuba",
  "Curacao",
  "Dhekelia",
  "Dinamarca",
  "Djibouti",
  "Dominica",
  "Egito",
  "Emirados Árabes Unidos",
  "Equador",
  "Eritréia",
  "Eslováquia",
  "Eslovênia",
  "Espanha",
  "Estados Unidos",
  "Estônia",
  "Etiópia",
  "Faroé",
  "Fiji",
  "Filipinas",
  "Finlândia",
  "França",
  "Gabão",
  "Gâmbia",
  "Gana",
  "Geórgia",
  "Geórgia do Sul e Sandwich do Sul",
  "Gibraltar",
  "Granada",
  "Grécia",
  "Groelândia",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guiana",
  "Guiné",
  "Guiné Equatorial",
  "Guiné-Bissau",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungria",
  "Iémen",
  "Ilha Bouvet",
  "Ilha de Man",
  "Ilha do Natal",
  "Ilha Norfolk",
  "Ilha Wake",
  "Ilhas Ashmore and Cartier",
  "Ilhas Caimão",
  "Ilhas Cook",
  "Ilhas do mar de Coral",
  "Ilhas dos Cocos",
  "Ilhas Falkland",
  "Ilhas Heard e McDonald",
  "Ilhas Marshall",
  "Ilhas Paracel",
  "Ilhas Pitcairn",
  "Ilhas Salomão",
  "Ilhas Turcas e Caicos",
  "Ilhas Virgens Americanas",
  "Ilhas Virgens Britânicas",
  "Índia",
  "Indonésia",
  "Irã",
  "Iraque",
  "Irlanda",
  "Islândia",
  "Israel",
  "Itália",
  "Jamaica",
  "Jan Mayen",
  "Japão",
  "Jersey",
  "Jordânia",
  "Kosovo",
  "Kuwait",
  "Laos",
  "Lesoto",
  "Letônia",
  "Líbano",
  "Libéria",
  "Líbia",
  "Liechtenstein",
  "Lituânia",
  "Luxemburgo",
  "Macau",
  "Macedônia",
  "Madagascar",
  "Malásia",
  "Malávi",
  "Maldivas",
  "Mali",
  "Malta",
  "Marianas do Norte",
  "Marrocos",
  "Maurícia",
  "Mauritânia",
  "México",
  "Micronésia",
  "Moçambique",
  "Moldávia",
  "Mônaco",
  "Mongólia",
  "Monserrate",
  "Montenegro",
  "Mundo",
  "Namíbia",
  "Nauru",
  "Ilha Navassa",
  "Nepal",
  "Nicarágua",
  "Níger",
  "Nigéria",
  "Niue",
  "Noruega",
  "Nova Caledónia",
  "Nova Zelândia",
  "Omã",
  "Países Baixos",
  "Palau",
  "Panamá",
  "Papua-Nova Guiné",
  "Paquistão",
  "Paraguai",
  "Peru",
  "Polinésia Francesa",
  "Polônia",
  "Porto Rico",
  "Portugal",
  "Quênia",
  "Quirguistão",
  "Quiribati",
  "Reino Unido",
  "República Centro-Africana",
  "República Dominicana",
  "Romênia",
  "Ruanda",
  "Rússia",
  "Salvador",
  "Samoa",
  "Samoa Americana",
  "Santa Helena",
  "Santa Lúcia",
  "São Bartolomeu",
  "São Cristóvão e Neves",
  "San Marino",
  "São Martinho",
  "São Pedro e Miquelon",
  "São Tomé e Príncipe",
  "São Vicente e Granadinas",
  "Sara Ocidental",
  "Seicheles",
  "Senegal",
  "Serra Leoa",
  "Sérvia",
  "Singapura",
  "Sint Maarten",
  "Síria",
  "Somália",
  "Spratly Islands",
  "Sri Lanca",
  "Suazilândia",
  "Sudão",
  "Sudão do Sul",
  "Suécia",
  "Suíça",
  "Suriname",
  "Svalbard e Jan Mayen",
  "Tailândia",
  "Taiwan",
  "Tajiquistão",
  "Tanzânia",
  "Timor Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trindade e Tobago",
  "Tunísia",
  "Turcomenistão",
  "Turquia",
  "Tuvalu",
  "Ucrânia",
  "Uganda",
  "Uruguai",
  "Uzbequistão",
  "Vanuatu",
  "Vaticano",
  "Venezuela",
  "Vietnã",
  "Wallis e Futuna",
  "Zâmbia",
  "Zimbabué",
];
